name:
on:
  push:
    branches: [ main ]

jobs:
  redeply_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the Prod server
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.known_hosts }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key root@"${{ secrets.MY_IP }}" -t "cd Portfolio/ && git pull origin main && export PATH=/root/.nvm/versions/node/v24.15.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && cd apps/web && pnpm run build && pm2 restart fe-server"   
